### ISSUE TITLE
EFCore InMemory

### ISSUE THREAD

**Issue by rstropek** [softawaregmbh/consulting-netcore-microservices-sample#3]
@PendelinP Suggestion: Let's use EFCore InMemory DBContext. Simple to implement, closer to real project. What do you think?

**Comment by PendelinP** [comment]
Yeah - seems to be a nice idea ;) The motivation behind the in-memory implementation was the self study assignment ;)

**Comment by rstropek** [comment]
Self-study could be to replace EFCore InMemory -> SqlServer?

**Comment by PendelinP** [comment]
Perfect - let's do it that way ;) Thanks for your thoughts.

**Comment by rstropek** [comment]
Will do the changes.
